apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: api-womb
  name: api-womb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-womb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: api-womb
    spec:
      containers:
        - image: womb
          name: api-womb
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
