apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-womb
  name: db-womb
spec:
  replicas: 1
  selector:
    io.kompose.service: db-womb
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: db-womb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: womb
            - name: MYSQL_PASSWORD
              value: admin1234
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: admin
          image: ' '
          name: db-womb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-womb
      restartPolicy: Always
      volumes:
        - name: db-womb
          persistentVolumeClaim:
            claimName: db-womb
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - db-womb
        from:
          kind: ImageStreamTag
          name: db-womb:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
