apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: db-womb
  name: db-womb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-womb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: db-womb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: womb
            - name: MYSQL_PASSWORD
              value: admin1234
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: admin
          image: mysql:latest
          name: db-womb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-womb
      restartPolicy: Always
      volumes:
        - name: db-womb
          persistentVolumeClaim:
            claimName: db-womb
status: {}
