
version: '3'

services:
  db-womb:
    container_name: db-womb
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'womb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin1234'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-womb:/var/lib/mysql
    networks:
      - backend
  api-womb:
    container_name: api-womb
    image: womb
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - db-womb
    networks:
      - backend
volumes:      
  db-womb:
networks:
  backend:          
